from estrutura_da_arvore_de_decisao.arvore_decisao import Arvore_Decisao
from estrutura_da_arvore_de_decisao.arvore_decisao import Pergunta
from estrutura_da_arvore_de_decisao.arvore_decisao import Folha