from arquiteturas_rede_neural.arquiteturas import criar_arquitetura_1
from arquiteturas_rede_neural.arquiteturas import criar_arquitetura_2
from arquiteturas_rede_neural.arquiteturas import criar_arquitetura_3
from arquiteturas_rede_neural.arquiteturas import criar_arquitetura_4
